name: parkease
description: A Smart Parking App built with Flutter and Firebase.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core & Auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # State Management & Navigation
  provider: ^6.1.2
  
  # Open-Source Maps (Alternative to Google Maps)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  
  # UI & Utilities
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true # <-- Notice this is flush against the left, NOT inside dependencies!

  # assets:
  #   - assets/images/
  #   - assets/icons/