// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi7vwYQpfhG8HbsPwyHi1nBTywk3UuVOY',
    appId: '1:219224923897:web:132ee47e97760a98514c28',
    messagingSenderId: '219224923897',
    projectId: 'parkease-booking-d840d',
    authDomain: 'parkease-booking-d840d.firebaseapp.com',
    storageBucket: 'parkease-booking-d840d.firebasestorage.app',
    measurementId: 'G-0RM4NZZRPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZEzuUCd41xe5rcCKb1CHKBNtFPVWUCE',
    appId: '1:219224923897:android:8966c7cf0bbd763e514c28',
    messagingSenderId: '219224923897',
    projectId: 'parkease-booking-d840d',
    storageBucket: 'parkease-booking-d840d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUr524w-xNpOMrXH0w_L3LOCNO2HHhq4',
    appId: '1:219224923897:ios:bfb322423c0e408b514c28',
    messagingSenderId: '219224923897',
    projectId: 'parkease-booking-d840d',
    storageBucket: 'parkease-booking-d840d.firebasestorage.app',
    iosClientId: '219224923897-jr5ff0sn2eo714vn7osiup0ckievorvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkease2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZUr524w-xNpOMrXH0w_L3LOCNO2HHhq4',
    appId: '1:219224923897:ios:bfb322423c0e408b514c28',
    messagingSenderId: '219224923897',
    projectId: 'parkease-booking-d840d',
    storageBucket: 'parkease-booking-d840d.firebasestorage.app',
    iosClientId: '219224923897-jr5ff0sn2eo714vn7osiup0ckievorvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkease2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi7vwYQpfhG8HbsPwyHi1nBTywk3UuVOY',
    appId: '1:219224923897:web:749b23ae1ea2db4c514c28',
    messagingSenderId: '219224923897',
    projectId: 'parkease-booking-d840d',
    authDomain: 'parkease-booking-d840d.firebaseapp.com',
    storageBucket: 'parkease-booking-d840d.firebasestorage.app',
    measurementId: 'G-8Z2Q39BP2B',
  );
}
